version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0

  prebuild:
    commands:
      - echo Restore started on `date`
      - dotnet restore 
  build:
    commands:      
      - dotnet build -c Release ./TestAPI.csproj
      - dotnet test -c Release 