version: 0.2

phases:

  pre_build:
    commands:
      - echo Restore started on `date`
      - aws --version
      # - dotnet restore
      - echo Logging into Amazon ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 365638482223.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=365638482223.dkr.ecr.us-east-1.amazonaws.com/rjecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $COMMIT_HASH
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}' ) 
      - echo $IMAGE_TAG
  build:
    commands:      
      # - dotnet build -c Release ./Api/TestAPI.csproj
      # - dotnet test -c Release
      - echo Build started on `date`
      - echo Building the docker image
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker images
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file
      - printf '[{"name":"testapiapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json